services:
  cursos:
    build:
      context: .
      dockerfile: Dockerfile
    image: captwhite/cursos:local
    pull_policy: never
    container_name: cursos
    restart: always
    ports:
      - "8070:4321"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
