export type MenuTab = 'Cursos' | 'IA' | 'Tab3' | 'Tab4' | 'Tab5' | 'Tab6';

export interface DocItem {
  filename: string;
  menutab: MenuTab;
  id: string;
  slug: string;
  description: string;
  chapter: string;
}

export const docList: DocItem[] = [
  {
    filename: 'docker.md',
    menutab: 'Cursos',
    id: 'docker',
    slug: 'docker',
    description: 'Docker',
    chapter: '1',
  },  
  {
    filename: 'docker-midu.md',
    menutab: 'Cursos',
    id: 'docker-midu',
    slug: 'docker-midu',
    description: 'Midudev',
    chapter: '1.1',
  },  
  {
    filename: 'docker-fherrera.md',
    menutab: 'Cursos',
    id: 'docker-fherrera',
    slug: 'docker-fherrera',
    description: 'Fernando Herrera',
    chapter: '1.2',
  },  
  {
    filename: 'astro.md',
    menutab: 'Cursos',
    id: 'astro',
    slug: 'astro',
    description: 'Astro',
    chapter: '3',
  },   
  {
    filename: 'astro-midu.md',
    menutab: 'Cursos',
    id: 'astro-midu',
    slug: 'astro-midu',
    description: 'Midudev',
    chapter: '3.1',
  },  
 {
    filename: 'python.md',
    menutab: 'Cursos',
    id: 'python',
    slug: 'python',
    description: 'Python',
    chapter: '4',
  },   
  {
    filename: 'python-midu.md',
    menutab: 'Cursos',
    id: 'python-midu',
    slug: 'python-midu',
    description: 'Midudev',
    chapter: '4.1',
  },  
  {
    filename: 'python-fazt.md',
    menutab: 'Cursos',
    id: 'python-fazt',
    slug: 'python-fazt',
    description: 'Fazt',
    chapter: '4.2',
  },  
  {
    filename: 'node.md',
    menutab: 'Cursos',
    id: 'node',
    slug: 'node',
    description: 'Node.js',
    chapter: '6',
  },   
  {
    filename: 'node-midu.md',
    menutab: 'Cursos',
    id: 'node-midu',
    slug: 'node-midu',
    description: 'Midudev',
    chapter: '6.1',
  },  
  {
    filename: 'node-fazt.md',
    menutab: 'Cursos',
    id: 'node-fazt',
    slug: 'node-fazt',
    description: 'Fazt',
    chapter: '6.2',
  },  
  {
    filename: 'next.md',
    menutab: 'Cursos',
    id: 'next',
    slug: 'next',
    description: 'Next.js',
    chapter: '7',
  },   
  {
    filename: 'next-midu.md',
    menutab: 'Cursos',
    id: 'next-midu',
    slug: 'next-midu',
    description: 'Midudev',
    chapter: '7.1',
  },  
  {
    filename: 'react.md',
    menutab: 'Cursos',
    id: 'react',
    slug: 'react',
    description: 'React',
    chapter: '8',
  },   
  {
    filename: 'react-midu.md',
    menutab: 'Cursos',
    id: 'react-midu',
    slug: 'react-midu',
    description: 'Midudev',
    chapter: '8.1',
  },  
  {
    filename: 'react-fazt.md',
    menutab: 'Cursos',
    id: 'react-fazt',
    slug: 'react-fazt',
    description: 'Fazt',
    chapter: '8.2',
  },    
  {
    filename: 'typescript.md',
    menutab: 'Cursos',
    id: 'typescript',
    slug: 'typescript',
    description: 'TypeScript',
    chapter: '10',
  },   
  {
    filename: 'typescript-midu.md',
    menutab: 'Cursos',
    id: 'typescript-midu',
    slug: 'typescript-midu',
    description: 'Midudev (1 y 2)',
    chapter: '10.1',
  },     
 {
    filename: 'wordpress.md',
    menutab: 'Cursos',
    id: 'wordpress',
    slug: 'wordpress',
    description: 'WordPress',
    chapter: '11',
  },   
  {
    filename: 'wordpress-midu.md',
    menutab: 'Cursos',
    id: 'wordpress-midu',
    slug: 'wordpress-midu',
    description: 'Midudev',
    chapter: '11.1',  
  },
 {
    filename: 'git-github.md',
    menutab: 'Cursos',
    id: 'git-github',
    slug: 'git-github',
    description: 'Git y GitHub',
    chapter: '12',
  },   
  {
    filename: 'git-github-midu.md',
    menutab: 'Cursos',
    id: 'git-github-midu',
    slug: 'git-github-midu',
    description: 'Midudev',
    chapter: '12.1',  
  },
   {
    filename: '8n8.md',
    menutab: 'Cursos',
    id: '8n8',
    slug: '8n8',
    description: '8n8',
    chapter: '13',
  },   
  {
    filename: '8n8-midu.md',
    menutab: 'Cursos',
    id: '8n8-midu',
    slug: '8n8-midu',
    description: 'Midudev',
    chapter: '13.1',  
  },  
  {
    filename: 'cloudflare.md',
    menutab: 'Cursos',
    id: 'cloudflare',
    slug: 'cloudflare',
    description: 'Cloudflare',
    chapter: '14',
  },   
  {
    filename: 'cloudflare-midu.md',
    menutab: 'Cursos',
    id: 'cloudflare-midu',
    slug: 'cloudflare-midu',
    description: 'Midudev',
    chapter: '14.1',  
  },  
  {
    filename: 'css.md',
    menutab: 'Cursos',
    id: 'css',
    slug: 'css',
    description: 'CSS',
    chapter: '15',
  },   
  {
    filename: 'css-midu.md',
    menutab: 'Cursos',
    id: 'css-midu',
    slug: 'css-midu',
    description: 'Midudev',
    chapter: '15.1',  
  },  
  {
    filename: 'html.md',
    menutab: 'Cursos',
    id: 'html',
    slug: 'html',
    description: 'HTML',
    chapter: '16',
  },   
  {
    filename: 'html-midu.md',
    menutab: 'Cursos',
    id: 'html-midu',
    slug: 'html-midu',
    description: 'Midudev',
    chapter: '16.1',  
  },  
  {
    filename: 'tailwind.md',
    menutab: 'Cursos',
    id: 'tailwind',
    slug: 'tailwind',
    description: 'Tailwind CSS',
    chapter: '17',
  },   
  {
    filename: 'tailwind-midu.md',
    menutab: 'Cursos',
    id: 'tailwind-midu',
    slug: 'tailwind-midu',
    description: 'Midudev',
    chapter: '17.1',  
  },  
 {
    filename: 'zustand.md',
    menutab: 'Cursos',
    id: 'zustand',
    slug: 'zustand',
    description: 'Zustand',
    chapter: '18',
  },   
  {
    filename: 'zustand-midu.md',
    menutab: 'Cursos',
    id: 'zustand-midu',
    slug: 'zustand-midu',
    description: 'Midudev',
    chapter: '18.1',  
  },  
 {
    filename: 'javascript.md',
    menutab: 'Cursos',
    id: 'javascript',
    slug: 'javascript',
    description: 'JavaScript',
    chapter: '19',
  },   
  {
    filename: 'javascript-fazt.md',
    menutab: 'Cursos',
    id: 'javascript-fazt',
    slug: 'javascript-fazt',
    description: 'Fazt',
    chapter: '19.1',  
  },  
  {
    filename: 'nest.md',
    menutab: 'Cursos',
    id: 'nest',
    slug: 'nest',
    description: 'NestJS',
    chapter: '20',
  },   
  {
    filename: 'nest-fazt.md',
    menutab: 'Cursos',
    id: 'nest-fazt',
    slug: 'nest-fazt',
    description: 'Fazt',
    chapter: '20.1',  
  },
  {
    filename: 'opencode.md',
    menutab: 'IA',
    id: 'opencode',
    slug: 'opencode',
    description: 'OpenCode',
    chapter: '1',
  },  
  {
    filename: 'opencode-midu.md',
    menutab: 'IA',
    id: 'opencode-midu',
    slug: 'opencode-midu',
    description: 'Midudev',
    chapter: '1.1',
  }, 
  {
    filename: 'opencode-fazt.md',
    menutab: 'IA',
    id: 'opencode-fazt',
    slug: 'opencode-fazt',
    description: 'Fazt',
    chapter: '1.2',
  },    
  {
    filename: 'desarrollo-ia.md',
    menutab: 'IA',
    id: 'desarrollo-ia',
    slug: 'desarrollo-ia',
    description: 'Desarrollo de I.A.',
    chapter: '2',
  },  
    {
    filename: 'desarrollo-ia-brais.md',
    menutab: 'IA',
    id: 'desarrollo-ia-brais',
    slug: 'desarrollo-ia-brais',
    description: 'Brais',
    chapter: '2.1',
  },  
  {
    filename: 'desarrollo-ia-midu.md',
    menutab: 'IA',
    id: 'desarrollo-ia-midu',
    slug: 'desarrollo-ia-midu',
    description: 'Midudev',
    chapter: '2.2',
  },  
  {
    filename: 'inteligencia-artificial.md',
    menutab: 'IA',
    id: 'inteligencia-artificial',
    slug: 'inteligencia-artificial',
    description: 'Inteligencia Artificial',
    chapter: '3',
  },   
  {
    filename: 'inteligencia-artificial-midu.md',
    menutab: 'IA',
    id: 'inteligencia-artificial-midu',
    slug: 'inteligencia-artificial-midu',
    description: 'Midudev',
    chapter: '3.1',
  },   
];

export const docMapById = new Map<string, DocItem>(
  docList.map(item => [item.id, item])
);

export const docMapBySlug = new Map<string, DocItem>(
  docList.map(item => [item.slug, item])
);
